# in languages.toml
[[language]]
name = "python"
language-servers = ["pyright", "ruff", "pylyzer"]
[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
[language-server.ruff]
command = "ruff"
args = ["server"]
[language-server.pylyzer]
command = "pylyzer"
args = ["--server"]

[[language]]
name = "rust"
auto-format = true

roots = [
  "Cargo.toml",
  "Cargo.lock"
]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rs|rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
shebangs = ["rust-script", "cargo"]
auto-format = true
comment-tokens = ["//", "///", "//!"]
block-comment-tokens = [
  { start = "/*", end = "*/" },
  { start = "/**", end = "*/" },
  { start = "/*!", end = "*/" },
]
language-servers = [ "rust-analyzer" ]
indent = { tab-width = 4, unit = "    " }
persistent-diagnostic-sources = ["rustc", "clippy"]

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false
[language-server.rust-analyzer.config.check]
command = "clippy"


# JavaScript
[[language]]
name = "javascript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
  "tailwindcss-ls",
  "emmet-ls"
]
auto-format = true
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }

# TypeScript
[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
  "tailwindcss-ls",
  "emmet-ls"
]
auto-format = true
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }

# TSX
[[language]]
name = "tsx"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
  "tailwindcss-ls",
  "emmet-ls"
]
auto-format = true
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }

# JSX
[[language]]
name = "jsx"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
  "tailwindcss-ls",
  "emmet-ls"
]
auto-format = true
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }

# HTML
[[language]]
name = "html"
language-servers = ["tailwindcss-language-server", "emmet-ls"]
formatter = { command = "prettierd", args = [".html"] }
auto-format = true

# CSS
[[language]]
name = "css"
language-servers = ["tailwindcss-language-server", "emmet-ls"]
formatter = { command = "prettierd", args = [".css"] }
auto-format = true

# SCSS
[[language]]
name = "scss"
language-servers = ["tailwindcss-language-server", "emmet-ls"]
formatter = { command = "prettierd", args = [".scss"] }
auto-format = true
